br_utils.create_plugin ({	
'name':'content_config_attrs',
'author':'Stephen Conover',
'description':'',
'regex_urls': ["/admin/configuration/attributes/edit_attribute.jsp"],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc) {
	var params = {};
	
	//params.url = doc.location.href;
	//params.title = jQuery("title", doc).html();
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	var cond1 = true;
	//var cond2 = (params['title']||"").indexOf('some-value') > -1;

	return (cond1);
},
'content': content_config_attrs,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_config_attrs(params) {
	var that = this;
	//AH too slow to go fast :(
	//var IwantItbroken = false;
	//this.faster = function(){IwantItbroken = true;}
	this.after_page_load = function() {
		//this.load_enhancements();
		this.initiate_display();
	};
	this.convert_links = function() {
		//setTimeout(function(){
			if(jQuery(".sangfroid_converted_link",doc).length <= 1 /*&& IwantItbroken*/) {
				makeLinks();
			}
		//},500);
	};
	function makeLinks(){
		if(jQuery('a[href*="rule_editor"]',doc).length > 0){
			jQuery('a[href*="rule_editor"]',doc).each(function () {
				configHref = this.href;
				hrefParams = configHref.split('\'');
				link = hrefParams[1].replace(/\\/g, '');
				if(link.indexOf("popup") > -1){
					link = link.replace("&popup=1", "");
				}
				jQuery(this).addClass("sangfroid_converted_link");
				this.href = link;
			});
			jQuery(".sangfroid_converted_link", doc).css({
				'color' : that.pm.getCharPref("color_text1"),
				'background-color' : that.pm.getCharPref("color_main1")
			});
		}
	}
	
	/* AH - combining attribute_helper.brc.js */
	
	this.attribute_loader = function() {
		attr_notification();
		setTimeout(function(){ build_loader(); },500);
	};
	
	function attr_notification(){
		var url = params['url']||"";
		var is_prod = br_utils.is_prod_site(url);
		var level = "";
		if(is_prod){
			level = "prod";
		}
		br_log.page("<div id='br_log_attribute_loader_location'/>",level);
	}
	var build_loader = function () {
		var html = br_load.template("chrome://sangfroid/content/templates/attr-loader.html");
		html.then(function (template) {
			var comp_crap = jQuery("#sangfroid_helper", doc);
			if (comp_crap.length > 0) {
				if (jQuery(comp_crap).css("display") === "none") {
					jQuery("#sangfroid_helper", doc).show();
				} else {
					jQuery("#sangfroid_helper", doc).hide();
				}
			} else {
				//jQuery("#general", doc).prepend(template());
				//jQuery("#tab_general", doc).prepend(template());
				jQuery("#br_log_attribute_loader_location", doc).parent().append(template());					
			}
			//jQuery("#general", doc).children("table").css("width", "80%");
			//jQuery("#tab_general", doc).children("table").css("width", "80%");
		})
		jQuery(".com_attr_send", doc).live("click", function () {
			try {
				var box = jQuery("[name='attributes']", doc).val(); // get the values from text area
				br_log.firebug(box);
				var index = box.indexOf("\n"); // get index of new line character
				while (index > 0) {
					if (jQuery("[name='tType']", doc)[0].checked) {
						jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box.substring(0, index));
						jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box.substring(0, index));
					} else {
						if (box.substring(0, index).indexOf(",") > -1) {
							jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box.substring(0, index).split(",")[0]);
							jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box.substring(0, index).split(",")[1]);
						} else {
							jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box.substring(0, index));
							jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box.substring(0, index));
						}
					}
					doc.getElementById("add_entry").parentNode.click();
					box = box.substring(index + 1);
					index = box.indexOf("\n");
				}
				if (jQuery("[name='tType']", doc)[0].checked) {
					jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box);
					jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box);
				} else {
					if (box.indexOf(",") > -1) {
						jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box.split(",")[0]);
						jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box.split(",")[1]);
					} else {
						jQuery("[name='_BM_MENU_ITEM_TEXT']", doc).val(box);
						jQuery("[name='_BM_MENU_ITEM_VALUE']", doc).val(box);
					}
				}
				doc.getElementById("add_entry").parentNode.click();
			} catch (e) {
				br_log.firebug(e)
			}
		})
	};
	
	this.get_menu = function () {
		var me = this;
		//this.auto_sync(me);

		var m = br_menu(me.doc, me)
			.add_separator("br_tools", "Tools")
			.add_button_with_icon("br_convert", "Convert Links", "Convert",
				"chrome://sangfroid/content/img/html.png", function () {
				me.convert_links();
			});
			if(jQuery("[name='_BM_MENU_ADMIN']", doc).length > 0){
				//menu attributes
				m.add_button_with_icon("br_loader", "Attribute Loader", "Loader",
					"chrome://sangfroid/content/img/add.png", function () {
					me.attribute_loader();
				});
			}
		return m;
	};
	/*
	function doTheThing(){
		actionBar = jQuery("form[name='bmForm']>table",doc).last().children("tbody").children("tr");
		actionBar.prepend("<td><table cellspacing='0' cellpadding='0' class='sangfroidStyle' id='configLinks' style='cursor: pointer;'><tbody><tr><td class='button-left'><img src='/img/button10.gif' class='button-left'></td><td nowrap='true' class='button-middle'><div style='margin: 0px 0px 1px;'><a href='#' id='link_butt' name='link_butt' class='button-text'>Make Config Links</a></div></td><td class='button-right'><img src='/img/button10.gif' class='button-right'></td></tr></tbody></table></td>");
		jQuery("#configLinks",doc).bind("click",function(){makeLinks();});				
	}*/
	this.get_script_type = function() {return "content_config_attrs";};
	
	//this.initiate_display = function() {doTheThing();};
}
content_config_attrs.prototype = new BR_Content();
