br_utils.create_plugin ({	
'name':'content_workflow_steps',
'author':'',
'description':'',
'regex_urls': ['admin\/commerce\/workflow\/steps.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc) {
	var params = {};
	
	//params.url = doc.location.href;
	//params.title = jQuery("title", doc).html();
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	var cond1 = true;

	return (cond1);
},
'content': content_workflow_steps,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_workflow_steps(params) {

	this.get_script_type = function() {return "content_workflow_steps";};
	this.get_filename = function() {};
	this.get_extension = function() {};
	this.get_local_directory = function() {};
	
	this.get_menu = function () {
		var me = this;
		//this.auto_sync(me);
		var m = br_menu(me.doc, me)
		.add_separator("br_editing", "Editor")
		.add_button_with_icon("br_open_temp", "Get Access List", "access",
			"chrome://sangfroid/content/img/creds.png", function () {
			me.get_access_list();
		})
		return m;
	};
	this.get_access_list = function() {
		var accessList = "";
		if(jQuery('li.x-tab-strip-active .x-tab-strip-text',doc).length > 0 && jQuery('li.x-tab-strip-active .x-tab-strip-text',doc).html() == "User Access Rights"){
			var typeList = "";
			var groupList = "";
			var stepList = "";
			//accessList = accessList + "Access Rights:\n";
			jQuery('div.profile-tabs:not(.x-hide-display) td:nth-of-type(1) tr input:checked',doc).each(function(){
				typeList = typeList + "\t" + jQuery(this).parent().next().next().text() + "\n";
			});
			//accessList = accessList + "Groups:\n";
			jQuery('div.profile-tabs:not(.x-hide-display) td:nth-of-type(2) tr input:checked',doc).each(function(){
				groupList = groupList + "\t" + jQuery(this).parent().next().next().text() + "\n";
			});
			//accessList = accessList + "Performer Steps:\n";
			jQuery('div.profile-tabs:not(.x-hide-display) .x-grid3-row-selected td:nth-of-type(2) div',doc).each(function(){
				stepList = stepList + "\t" + jQuery(this).text() + "\n";
			});
			if(typeList == ""){
				accessList = accessList + "Access Rights:\n\tNo Access Rights are selected!\n";
			}else{
				accessList = accessList + "Access Rights:\n" + typeList;
			}
			if(groupList == ""){
				accessList = accessList + "Groups:\n\tNo Groups are selected!\n";
			}else{
				accessList = accessList + "Groups:\n" + groupList;
			}
			if(stepList == ""){
				accessList = accessList + "Performer Steps:\n\tNo Performer Steps are selected!\n";
			}else{
				accessList = accessList + "Performer Steps:\n" + stepList;
			}
			alert(accessList);
		}else{
			alert("Please open the User Access Rights tab of a Participant Profile");
		}
		
	}
}
content_workflow_steps.prototype = new BR_Content();
