br_utils.create_plugin ({	
'name':'content_config_rule_list',
'author':'',
'description':'',
'regex_urls': ['\/admin\/configuration\/rules\/list_rules',
				'\/admin\/configuration\/attributes\/list_attributes'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc) {
	var params = {};
	
	//params.url = doc.location.href;
	//params.title = jQuery("title", doc).html();
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	var cond1 = true;
	//var cond2 = (params['title']||"").indexOf('some-value') > -1;

	return (cond1);
},
'content': content_config_rule_list,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_config_rule_list(params) {
	/**
	 * content and elements on page
	 */
	 
	ruleType = br_utils.urlParam("rule_type") || "666";
	
	this.get_script_type = function() {return "content_config_rule_list";};
	
	this.get_filename = function() {};
	this.get_extension = function() {};
	this.get_local_directory = function() {};
	
	this.initiate_display = function() {
		this.make_notification();
	};
	this.make_notification = function(){
		var that = this;
		var url = params['url']||"";
		var is_prod = br_utils.is_prod_site(url);
		var level = "";
		if(is_prod){
			level = "prod";
		}
		br_log.page("<div id='br_log_tools_location'/>",level,function(){
			that.filter_menu(ruleType);
		});
	};
	this.filter_menu = function(ruleType){
		that = this;
		
		jQuery("#br_log_tools_location",doc).prepend("<input type='button' id='filter_hidden' value='Filter'/>");
		jQuery("#br_log_tools_location",doc).prepend("<select id='statusFilter' name='dropdownmenu' size=1 ><option value='All'>All<option value='1'>Active<option value='2'>Internal<option value='3'>Inactive</select>");
		switch(ruleType){
			case "1":
				jQuery("#br_log_tools_location",doc).prepend("<select id='areaFilter' name='dropdownmenu' size=1 ><option value='All'>All<option value='1'>Configuration<option value='2'>Selection<option value='3'>Both</select>");
			break;
			case "2":
				jQuery("#br_log_tools_location",doc).prepend("<select id='ajaxFilter' name='dropdownmenu' size=1><option value='All'>All<option value='Yes'>Yes<option value='No'>No</select></select>");
				jQuery("#br_log_tools_location",doc).prepend("<select id='areaFilter' name='dropdownmenu' size=1><option value='All'>All<option value='1'>Configuration<option value='2'>Selection<option value='3'>Both</select>");
			break;
			case "9":
				jQuery("#br_log_tools_location",doc).prepend("<select id='mandFilter' name='dropdownmenu' size=1><option value='All'>All<option value='Yes'>Yes<option value='No'>No</select>");
			break;
			case "11":
				jQuery("#br_log_tools_location",doc).prepend("<select id='ajaxFilter' name='dropdownmenu' size=1><option value='All'>All<option value='Yes'>Yes<option value='No'>No</select>");
				jQuery("#br_log_tools_location",doc).prepend("<select id='areaFilter' name='dropdownmenu' size=1 ><option value='All'>All<option value='1'>Configuration<option value='2'>Selection<option value='3'>Both</select>");
			break;
			case "666":
				jQuery("#br_log_tools_location",doc).prepend("<select id='dataFilter' name='dropdownmenu' size=1><option value='All'>All<option value='Text'>Text<option value='Float'>Float<option value='Integer'>Integer<option value='HTML'>HTML<option value='Boolean'>Boolean<option value='Currency'>Currency<option value='Date'>Date</select>");
				jQuery("#br_log_tools_location",doc).prepend("<select id='attrFilter' name='dropdownmenu' size=1><option value='All'>All<option value='Text Field'>Text Field<option value='Single Select Menu'>Single Select Menu<option value='Multi Select Menu'>Multi Select Menu<option value='Read Only'>Read Only<option value='Boolean'>Boolean<option value='Date'>Date</select>");
			break;
			default:
			break;
		}		
		jQuery("#br_log_tools_location",doc).prepend("<input type='button' id='color_code_it' value='Color Code It!'/><br/>");
		jQuery("#color_code_it",doc).click(function() {
			that.color_code(ruleType);
		});
		jQuery("#filter_hidden",doc).click(function() {
			that.filterRule(ruleType);
		});
	};
	
	this.color_code = function(ruleType){
		if(ruleType != "666"){
			jQuery("[name*='status']",doc).each(function(){
				var that = this;
				switch(that.value){
					case "1":
						jQuery(this).parent().parent().css('backgroundColor', '#99ccff');
					break;
					case "2":
						jQuery(this).parent().parent().css('backgroundColor', '#99f');
					break;
					case "3":
						jQuery(this).parent().parent().css('backgroundColor', '#ddd');
					break;
					default:
					break;
				}
			});
		}else{
			jQuery("[name='bmForm'] table:nth-of-type(1) tr[class] td:nth-of-type(11)",doc).each(function(){
				var that = this;
				switch(that.innerHTML.trim().split("&")[0]){
					case "Active":
						jQuery(this).parent().css('backgroundColor', '#99ccff');
					break;
					case "Internal":
						jQuery(this).parent().css('backgroundColor', '#99f');
					break;
					case "Inactive":
						jQuery(this).parent().css('backgroundColor', '#ddd');
					break;
					default:
					break;
				}
			});
		}
	};
	
	this.filterRule = function(ruleType){
		var status = "All";
		var area = "All";
		var ajax = "All";
		var mand = "All";
		var type = "All";
		var attr = "All";
		var data = "All";
		switch(ruleType){
			case "1":
				status = jQuery("#statusFilter",doc).val();
				area = jQuery("#areaFilter",doc).val();
				
				statusList = jQuery("[name*='status']",doc);
				areaList = jQuery("[name*='rule_area']",doc);
			break;
			case "2":
				status = jQuery("#statusFilter",doc).val();
				area = jQuery("#areaFilter",doc).val();
				ajax = jQuery("#ajaxFilter",doc).val();
				
				statusList = jQuery("[name*='status']",doc);
				areaList = jQuery("[name*='rule_area']",doc);
				ajaxList = jQuery("[name='bmForm'] table:nth-of-type(2) tr[class] td:nth-of-type(5)",doc);
			break;
			case "9":
				status = jQuery("#statusFilter",doc).val();
				mand = jQuery("#mandFilter",doc).val();
				
				statusList = jQuery("[name*='status']",doc);
				mandList = jQuery("[name='bmForm'] table:nth-of-type(2) tr[class] td:nth-of-type(4)",doc);
			break;
			case "11":
				status = jQuery("#statusFilter",doc).val();
				area = jQuery("#areaFilter",doc).val();
				ajax = jQuery("#ajaxFilter",doc).val();
				
				statusList = jQuery("[name*='status']",doc);
				areaList = jQuery("[name*='rule_area']",doc);
				ajaxList = jQuery("[name='bmForm'] table:nth-of-type(2) tr[class] td:nth-of-type(5)",doc);
			break;
			case "666":
				status = jQuery("#statusFilter",doc).val();
				attr = jQuery("#attrFilter",doc).val();
				data = jQuery("#dataFilter",doc).val();
				
				statusList = jQuery("[name='bmForm'] table:nth-of-type(1) tr[class] td:nth-of-type(11)",doc);
				attrList = jQuery("[name='bmForm'] table:nth-of-type(1) tr[class] td:nth-of-type(6)",doc);
				dataList = jQuery("[name='bmForm'] table:nth-of-type(1) tr[class] td:nth-of-type(7)",doc);
			break;
			default:
				status = jQuery("#statusFilter",doc).val();
				
				statusList = jQuery("[name*='status']",doc);
			break;
		}
		iterator = 1;
		for(i=0; i<statusList.length; i++){
			display = false;
			statusBool = false;
			areaBool = false;
			ajaxBool = false;
			mandBool = false;
			attrBool = false;
			dataBool = false;
			statusVal = "";
			if(ruleType == "666"){
				switch(statusList[i].innerHTML.trim().split("&")[0]){
					case "Active":
						statusVal = "1";
					break;
					case "Internal":
						statusVal = "2";
					break;
					case "Inactive":
						statusVal = "3";
					break;
					default:
					break;
				}
			}else{
				statusVal = statusList[i].value;
			}
			if(statusVal == status || status == "All"){
				statusBool = true;
				if((area != "All" && areaList[i].value == area) || area == "All"){
					areaBool = true;
				}
				if((ajax != "All" && ajaxList[i].innerHTML.trim() == ajax) || ajax == "All"){
					ajaxBool = true;
				}
				if((mand != "All" && mandList[i].innerHTML.trim() == mand) || mand == "All"){
					mandBool = true;
				}
				if((attr != "All" && attrList[i].innerHTML.trim().split("&")[0] == attr) || attr == "All"){
					attrBool = true;
				}
				if((data != "All" && dataList[i].innerHTML.trim().split("&")[0] == data) || data == "All"){
					dataBool = true;
				}
			}
			if(ruleType == "666"){
				if(!(statusBool && areaBool && ajaxBool && mandBool && attrBool && dataBool)){
					jQuery(statusList[i],doc).parent().css('display', 'none');
				}else{
					jQuery(statusList[i],doc).parent().css('display', '');
				}
			}else{
				if(!(statusBool && areaBool && ajaxBool && mandBool && attrBool && dataBool)){
					jQuery(statusList[i],doc).parent().parent().css('display', 'none');
				}else{
					jQuery(statusList[i],doc).parent().parent().css('display', '');
				}
			}
		}
	};
}
content_config_rule_list.prototype = new BR_Content();
