br_utils.create_plugin ({	
'name':'content_data_tables',
'author':'Stephen Conover',
'description':'Runs on the Data Table Page',
'regex_urls': ['/admin/scripts/edit_tables.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc) {
	var params = {};
	
	//params.url = doc.location.href;
	//params.title = jQuery("title", doc).html();
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	var cond1 = true;
	//var cond2 = (params['title']||"").indexOf('some-value') > -1;

	return (cond1);
},
'content': content_data_tables,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_data_tables(params) {
	function tableSelect(){
		var addSearch = { childList: true }
		var whereLook = doc.querySelector("body");
		var run = false;
		findSearch = new MutationObserver(function (mutations) {
			if(jQuery("div.x-component>table.bm-multi-select-field input",doc).length > 0){
				jQuery("table.bm-multi-select-field label.x-form-cb-label",doc).each(function (){
					if(this.firstChild.textContent === "Search across tables"){
						this.id = "search_across";
					}
				});
				if(jQuery("#search_across",doc).prev("input").attr("checked")){
					if(jQuery("div.x-combo-list-inner",doc).length > 0 && jQuery("#select_all",doc).length == 0){
						searchOpt = jQuery("div.x-combo-list-inner tbody",doc);
						searchOpt.prepend("<tr><td><table cellspacing='0' cellpadding='0' class='sangfroidStyle' id='select_all' style='cursor: pointer;'><tbody><tr><td class='button-left'><img src='/img/button10.gif' class='button-left'></td><td nowrap='true' class='button-middle'><div style='margin: 0px 0px 1px;'><a href='#' id='search_butt' name='search_butt' class='button-text'>Select All Tables</a></div></td><td class='button-right'><img src='/img/button10.gif' class='button-right'></td></tr></tbody></table></td></tr>");
						jQuery("#select_all",doc).bind("click",function(){checkBoxes(true);});
						searchOpt.prepend("<tr><td><table cellspacing='0' cellpadding='0' class='sangfroidStyle' id='deselect_all' style='cursor: pointer;'><tbody><tr><td class='button-left'><img src='/img/button10.gif' class='button-left'></td><td nowrap='true' class='button-middle'><div style='margin: 0px 0px 1px;'><a href='#' id='desearch_butt' name='desearch_butt' class='button-text'>Deselect All Tables</a></div></td><td class='button-right'><img src='/img/button10.gif' class='button-right'></td></tr></tbody></table></td></tr>");
						jQuery("#deselect_all",doc).bind("click",function(){checkBoxes(false);});
					}
					else{
						findSearch.disconnect();
					}
				}
			}
		});
		function checkBoxes(toCheck){
			jQuery("div.x-combo-list-inner input",doc).each(function() {
				if(toCheck && !(this.checked)){
					this.click();
				}
				else if(!(toCheck) && this.checked){
					this.click()
				}
			});
			jQuery("div.x-combo-list-inner",doc).scrollTop(0);
		}
		findSearch.observe(whereLook, addSearch);
	}
	this.get_script_type = function() {return "content_data_tables";};

	this.initiate_display = function() {tableSelect()};
}
content_data_tables.prototype = new BR_Content();
