br_utils.create_plugin ({
'name':'Run On Admin Page',
'author':'Aaron Hall',
'description':'Scripts Admin Page',
//first check
regex_urls:['/admin/index.jsp','/admin/scripts/search_script.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
 //passed to matches_page and content
'get_parameters':function(doc, jQuery) {
	var params = {};
	
	params.url = doc.location.href;
	params.title = jQuery("title", doc).html();
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
 //second check
'matches_page':function(p) {
	return br_utils.is_bmi_site();
},
//actual function
'content': content_admin,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_admin(params) {
	var jQuery = this.jQuery, doc = this.doc;
	
	function get_hostname_prefix() {
	  var url = doc.location.href;
	  var end = url.indexOf(".com") + 5;
	  url = url.substring(0, end);
	  
	  return url;
	}
	
	this.get_menu = function () {
		var me = this;
		//this.auto_sync(me);

		var m = br_menu(me.doc, me)
			.add_separator("br_tools", "Tools")
			.add_button_with_icon("br_gss", "Global Script Search", "Global Script Search",
				"chrome://sangfroid/content/img/find.png", function () {
				searchUrl = "admin/scripts/search_script.jsp";
				if(params.url.indexOf("?gss=true") < 0) searchUrl = searchUrl + "?gss=true";
				doc.location.href = get_hostname_prefix() + searchUrl;
				//br_log.notify(me.get_hostname());
			});

		return m;
	};
	
}
content_admin.prototype = new BR_Content();
