br_utils.create_plugin ({	
'name':'Homepage Plugin',
'author':'Jason Manners',
'description':'Enables version control for the custom homepage page in bigmachines',
regex_urls:['setup_home_page.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc, jQuery) {
	var params = {};
	
	params.url = doc.location.href;
	params.title = jQuery("title", doc).html();
	params.mode = jQuery("input[name='mode']", doc).attr("value");
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(p) {
	var cond1 = (p['url']||"").indexOf('setup_home_page.jsp') > -1;
	var cond2 = (p['title']||"").indexOf('Home Page Set Up') > -1;
	var cond3 = (p['mode']) == "HTML"; //.indexOf('HTML');
	
	return (cond1 && cond2 && cond3);
},
'content': content_homepage,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_homepage(params) {
		var jQuery = this.jQuery, doc = this.doc;
	/**
	 * content and elements on page
	 */
	
	this.get_script_type = function() {return "content_homepage";};
	this.get_script = function() {
		var textarea = "profile";
		
		var ret = jQuery("textarea[name='"+textarea+"']",doc).val();

		return ret;
	};
	/**
	 * File naming and directories -
	 * 
	 * These functions are called whenever the plugin 
	 * is making a decision about where to save a file
	 */
	this.get_filename = function() {
		return "HomePage";
	};
	this.get_extension = function() {
		return ".html";
	};
	this.get_local_directory = function() {
		return "\\";
	};
	/**
	 * Entry points - 
	 * These functions are called by the firefox plugin directly
	 */
	//this.on_launch_and_save = function() {	}
	this.on_page_load = function() { 
		this.initiate_display(); 
	};
	//this.read_from_file = function() {  };
	//this.faster = function();
	/**
	 * actions
	 */
	this.get_node_for_read = function() {
		var textarea = "profile";
		var node = jQuery("textarea[name='"+textarea+"']",doc).get(0);
		
		return node;
	}

	//this.initiate_display = function() {br_display.create_display_pane()};
	//this.save_script_to_disk = function() {  };
	//this.open_script_in_editor = function() {  };
}
content_homepage.prototype = new BR_Content();
