br_utils.create_plugin ({	
'name':'content_log_level',
'author':'',
'description':'',
'regex_urls': ['internaladmin/log/log4jadmin.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc) {
	var params = {};
	
	//params.url = doc.location.href;
	//params.title = jQuery("title", doc).html();
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	var cond1 = true;
	//var cond2 = (params['title']||"").indexOf('some-value') > -1;

	return (cond1);
},
'content': content_log_level,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function content_log_level(params) {
	/**
	 * content and elements on page
	 */
	
	this.get_script_type = function() {return "content_log_level";};
	this.on_page_load = function() {
		jQuery('#content table tr.view-header ~ tr:odd',doc).each(function (){
				this.style="background-color:LightGray;";
		});
	};
	
	this.initiate_display = function() {};
}
content_log_level.prototype = new BR_Content();
