br_utils.create_plugin ({	
'name':'IntegrationXSLLinks',
'author':'Kenny Browne',
'description':'Adds the links to the integrations and the xsl view from the action',
regex_urls: ['admin\/commerce\/actions\/edit_action.jsp','admin/commerce/processes/edit_process.jsp'],
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
'get_parameters':function(doc, jQuery) {
	var params = {};

	//params.title = jQuery("title", doc).html();
	params.url = doc.location.href;
	
	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(p) {
	return (true);
},
'content': IntegrationXSLLinks,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function IntegrationXSLLinks(params) {
	var jQuery = this.jQuery, doc = this.doc;
	
	this.initiate_display = function() {};
	
	function build_array(list) {
		var result = [], integrationId, integrationName;
		jQuery("option",list).each(function(){
			integrationId = jQuery(this).attr("value");
			integrationName = jQuery(this).html();
			if(integrationName !== "Apply&nbsp;Modify&nbsp;Functions") {
				result.push({id: integrationId, name: integrationName});
			}
		});

		return result;
	}


	this.on_page_load = function() {
		var processId = jQuery("input[name='process_id']",doc).attr("value"),
			selected_IntegrationList = jQuery("select[name='integra_ids']",doc),
			unselected_IntegrationList = jQuery("select[name='integration_list']",doc),
			html_done = br_load.template("resource://br_templates/integration_block.html"),
			css_done = br_load.css("resource://br_templates/integration_block.css"),
			selected = [], unselected = [];
		
		if(selected_IntegrationList.length == 0) selected_IntegrationList = jQuery("select[name='initialImportIds']",doc);
		if(unselected_IntegrationList.length == 0) unselected_IntegrationList = jQuery("select[name='integrationList']",doc);
		function render(template, css) {
			if(jQuery("head #integration-css",doc).length < 1) {
				jQuery(css).attr("id", "integration-css");
				jQuery("head", doc).append(css);
			}

			var result = template({title: "Integration Links", process_id: processId, selected: selected, unselected: unselected});
			jQuery("#sangfroidIntRoot",doc).html(result);
		}

		//set the table
		jQuery(unselected_IntegrationList,doc).closest("table").parent().append("<div id='sangfroidIntRoot'></div>");

		selected = build_array(selected_IntegrationList);
		unselected = build_array(unselected_IntegrationList);

		Q.join(html_done, css_done, function(template, css) {
			render(template, css);
		});

		jQuery("a[id='>'], a[id='<']",doc).closest(".plain-button").click(function() {
			function async() {
				selected = build_array(selected_IntegrationList);
				unselected = build_array(unselected_IntegrationList);

				Q.join(html_done, css_done,function(template, css) {
					render(template, css);
				});
			}

			setTimeout(async, 0);
		});

		if(jQuery("select[name*='xsl_ids']",doc).length > 0){
			var selectedVal = jQuery("select[name*='xsl_ids']",doc).attr("value");
			var selectedName = jQuery("option[value*='" + selectedVal + "']",doc).html();
			var string = "<br/><img src='resource://br_images/logo.png'><b>Sangfroid Link to Printer Friendly XSL View:  </b><a href='/admin/commerce/views/edit_xslt.jsp?id=" + selectedVal + "'>" + selectedName + "</a>"
			jQuery("select[name*='xsl_ids']",doc).parent().append(string);
		}
	};
	this.plugin_created_successfully = function() {
		return(jQuery("#sangfroidIntRoot",doc).length > 0);
	}
		
}
IntegrationXSLLinks.prototype = new BR_Content();
