BR_Utils.create_plugin ({
'name':'quicker_links',
'author':'Kenny Browne',
'description':'Quick Links Helper',
/**
 * @param {DOM} doc The document object of the page that we are testing against
 * @return {Object} params A hashmap intended to hold information for identifying the page,
 */
regex_urls: ['quick_links.jsp'],
'get_parameters':function(doc) {
	var params = {};

	params.url = doc.location.href;

	return params;
},
/**
 * @param {Object} params A hashmap, usually generated by get_parameters
 * @return {Boolean} True if this plugin should be used on this page
 */
'matches_page':function(params) {
	//AH var cond1 = (params['url']||"").indexOf('.bigmachines.com') > -1;
	//var cond2 = (params['title']||"").indexOf('some-value') > -1;

	return true;
},
'content': quicker_links,
});
/**
 * @param {Object} params A hash map of information about the page
 * @extends BR_Content
 */
function quicker_links(params) {
var that = this;
var IwantItbroken = false;
this.faster = function(){IwantItbroken = true;}
this.stripslashes = function(str) {
	str=str.replace(/\\'/g,"'");
	str=str.replace(/\\/g,"");
	str=str.replace(/&amp;/g,"&");
	return str;
}

this.on_page_load = function() {
	//adds the deployment center and break option
	if(this.plugin_created_successfully != true){
		var processId = jQuery("select[name='process_id']",doc).attr("value"), setBreaker = "", segmentId = jQuery("select[name='segment_id']",doc).attr("value");
		if(typeof processId !== "undefined" && processId > -1){
			setBreaker = "<tr><td/><td align='center' style='white-space:nowrap;' colspan='3'><a id='isForDeploy' href='processes/schedule_events.jsp?process_id="+processId+"'><img src='resource://br_images/logo.png'>Go To Deployment Center</a>";
		}else if(typeof segmentId !== "undefined" && segmentId > -1){
			setBreaker = "<tr><td/><td align='center' style='white-space:nowrap;' colspan='3'><a id='isForDeploy' href='/admin/configuration/schedule_deployment.jsp?ref_type=2&ref_category=1&ref_id="+segmentId+"&attribute_category=2&_fromQlink=0'><img src='resource://br_images/logo.png'>Go To Deployment Center</a>";
		}
		if(setBreaker != ""){
			if(!IwantItbroken){
				setBreaker = setBreaker + "<br/><a id='isBreaking' href='#'><img src='resource://br_images/html.png'>Convert Links</a></td><td/></tr>";
			}else{
				setBreaker = setBreaker + "<td/></tr>";
			}
		}
		//alert(processId);
		jQuery("a[id='refresh']",doc).closest("table").closest("tbody").append(setBreaker);
		//jQuery("a[id='refresh']",doc).closest("table").closest("tbody").append(setDeploymentLink);
		jQuery("a[id='isBreaking']",doc).click(function(){that.runBreaking();});
		if(IwantItbroken){
			that.runBreaking();
		}
	}
}
this.runBreaking = function(){
	//Takes the existing js onclick and converts it to an href
	jQuery("a[class='tree' ]", doc).each(function(){
		var end = jQuery(this,doc).html().length, vars = jQuery('<div>',doc).append(jQuery(this,doc).clone()).remove().html(), varhref = "";
		//alert(vars);
		if(vars.indexOf("openPage('")>-1){
			varhref = vars.split("openPage('")[1].split("');")[0];
			//alert(varhref);
		}else{
			varhref = jQuery(this).attr("href");
		}
		varhref = that.stripslashes(varhref);
		varhref = unescape(varhref) + "&_fromQlink=1";
		if(vars.indexOf("onclick")>-1){
			//alert(varhref);
			newVal = "<a target='bmAdminWin' href=\"" + varhref + "\" class='" + jQuery(this).attr("class") + " sangfroid_converted_link' nowrap='true'>" + jQuery(this).html() + "</a>";
		}
		hrefs = jQuery(this).attr("href");
		if(vars.indexOf("onclick")>-1){
			//alert(newVal);
			jQuery(this).replaceWith(newVal);
		}else if(vars.indexOf("openPage")>-1){
			jQuery(this,doc).attr("href",varhref);
			jQuery(this,doc).addClass("sangfroid_converted_link");
		}
	});
	jQuery(".sangfroid_converted_link", doc).css({
		'color' : that.pm.getCharPref("color_text1"),
		'background-color' : that.pm.getCharPref("color_main1")
	});
}
this.plugin_created_successfully = function() {
	return(jQuery("#isBreaking",doc).length > 0);
}
this.initiate_display = function() {};
this.get_script_type = function() {return "quicker_links";};

}
quicker_links.prototype = new BR_Content();
